# Generated by Django 3.2 on 2024-05-30 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definicion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Desarrolladora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('añoFundacion', models.CharField(blank=True, max_length=10)),
                ('historia', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('preview', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.IntegerField(null=True, verbose_name=6)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='DesarrolloJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaLanzamiento', models.CharField(max_length=10)),
                ('desarrolladora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.desarrolladora')),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.juego')),
            ],
        ),
        migrations.AddField(
            model_name='desarrolladora',
            name='members',
            field=models.ManyToManyField(through='tienda.DesarrolloJuego', to='tienda.Juego'),
        ),
    ]
