# Generated by Django 5.0.1 on 2024-05-30 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desarrolladora',
            old_name='members',
            new_name='juegos',
        ),
    ]
