# Generated by Django 5.0.1 on 2024-05-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_rename_members_desarrolladora_juegos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='precio',
            field=models.IntegerField(max_length=6, null=True),
        ),
    ]
