# Generated by Django 5.0.1 on 2024-05-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_alter_juego_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AlterField(
            model_name='juego',
            name='precio',
            field=models.IntegerField(null=True),
        ),
    ]
