# Generated by Django 5.0.1 on 2024-05-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_categoria_nombre_alter_juego_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='srcImage',
            field=models.CharField(default='image', max_length=250),
        ),
    ]
