# Generated by Django 3.2 on 2024-06-06 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_juego_srcimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('comentario', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.juego')),
            ],
        ),
    ]
